apiVersion: v1
kind: Service
metadata:
  name: cloudflow-service
spec:
  type: NodePort
  selector:
    app: cloudflow-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
